# Generated by Django 4.0.5 on 2022-06-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_date_post_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
    ]
